= vscode_zx
:author: kounch
:revnumber: 1.1.2
:doctype: book
:email: kounch@users.noreply.github.com
:Revision:  1.0
:description: English Manual for vscode_zx
:keywords: Manual, English, vscode_zx, ZX Spectrum Next, BASIC
:icons: font 
:source-highlighter: rouge
:toc: left
:toc-title: Index
:toclevels: 4

<<<

== Description

Visual Studio Code Tasks and Scripts for NextBASIC and ZX Basic

Features:

- NextBASIC text to `.bas` file converter
- NextBASIC text renumbering
- Next BASIC auto formatter (Beta)
- Converts https://en.wikipedia.org/wiki/Block_Elements[unicode block elements] to Sinclair block graphics
- Supports non-printable characters using ` as escape character
- Task support to compile with ZX Basic
- Task integration to build (or convert) and run in ZEsarUX and CSpect emulators
- Works with Windows, MacOS and (possibly) Linux

Works best if used with:

- https://github.com/jsanjose/zxbasic-vscode[ZX Spectrum BASIC syntax highlighting for Visual Studio Code]
- https://github.com/remy/vscode-nextbasic[NextBASIC VSCode Syntax]

<<<

== Requirements

=== Download

A ZIP file with the latest version is available following https://github.com/kounch/vscode_zx/releases/latest[this link]

=== Software Requirements

- *Visual Studio Code*. Docs, downloads, etc. https://code.visualstudio.com/[here]

- *Python (version 3.6 or later)*. Docs, downloads, etc. https://www.python.org/[here]

- *ZX Basic*. Version 1.8.10 or later (.zip or .tar.gz). Docs, download, etcs. https://zxbasic.readthedocs.io[here]

- *NextLibs for ZX Basic*. More info http://zxbasic.uk/nextbuild/the-nextlibs/[here]. Download http://zxbasic.uk/nextbuild/download/[here]

=== Optional Software

- *hdfmonkey*. Download, http://files.zxdemo.org/gasman/speccy/hdfmonkey/[here]. Source Code https://github.com/gasman/hdfmonkey[here]. Binary for Windows http://uto.speccy.org/[here]

- *CSpect*. The latest development version can be found https://dailly.blogspot.com/[here]

- *ZEsarUX*. Docs, downloads, etc. https://github.com/chernandezba/zesarux[here]

<<<

== Installation

=== Basic Install

Install Python 3. On Windows, make sure that `py launcher` is selected as install option.

Create a directory structure like this:

    vscode_zx/
       |
       +--zxbasic/
       |
       +--Projects/
       |     |
       |     +--.vscode/
       |           |
       |           +--tasks.json
       |
       +--rennextbasic.py
       +--txt2nextbasic.py
       +--zxn_renumber.sh (zxn_renumber.bat on Windows)
       +--zxb_build.sh  (zxb_build.bat on Windows)

`Projects` directory can be renamed, but it *must* be next to  `txt2nextbasic.py`, `rennextbasic.py`, `zxb_build...` and `zxn_renumber...`.

Extract to `zxbasic` the full ZX Basic distribution, and then copy the file `nextlib.bas` (from `NextBuild-current.zip`: `NextBuildv5/ZXBC/library/`) to `zxbasic/library/`.

<<<

=== Installation with emulators

If you also want the option to compile and launch with the emulators, expand the directory structure like this:

    vscode_zx/
       |
       +--CSpect/
       +--ZEsarUX/
       +--zesaruxrc (zesaruxwinrc for Windows)
       +--zxbasic/
       |
       +--Projects/
       |     |
       |     +--.vscode/
       |           |
       |           +--tasks.json
       |
       +--rennextbasic.py
       +--txt2nextbasic.py
       +--zxn_renumber.sh (zxn_renumber.bat for Windows)
       +--zxb_build.sh  (zxb_build.bat for Windows)
       |
       +--hdfmonkey  (hdfmonkey.exe for Windows)

...and extract in `CSpect/` and `ZEsarUX/` both emulators (on MacOS, copy ZEsarUX app next to `zxb_build.sh`).

Now we have to set up the virtual SD card for each emulator.

<<<

==== CSpect configuration

After obtaining an SD image file, rename it as `systemnext.img`, and copy to `CSpect/` directory, with the files `enNextZX.rom` and `enNxtmmc.rom`. (Read https://www.specnext.com/latestdistro/[here] and http://www.zxspectrumnext.online/cspect/[here] to download).

Create the SD directory where the compiled software will be put:

[source,shell]
----
cd /(...)/vscode_zx/
hdfmonkey mkdir ./CSpect/systemnext.img /devel
----

Optionally, using `hdfmonkey`, we can replace the original distro `autoexec.bat` for the one availble in `ToInstall/autoexec.bas`. For example:

[source,shell]
----
hdfmonkey put ./CSpect/systemnext.img ./ToInstall/autoexec.bat /nextzxos/autoexec.bas
----

<<<

==== ZEsarUX Configuration

Edit the file `zesaruxrc` (`zesaruxwinrc` for Windows), writing after `--mmc-file` the full path to the file `tbblue.mmc`.

You can use the file that comes with the emulator distribution. If you prefer using another one, change its name to `tbblue.mmc`, and copy to `ZEsarUX/` directory.

The, create the structure in the virtual SD where the compiled software will be copied:

[source,shell]
----
cd /(...)/vscode_zx/
hdfmonkey mkdir ./ZEsarUX/tbblue.mmc /devel
----

If you are using MacOS:

[source,shell]
----
cd /(...)/vscode_zx/
hdfmonkey mkdir ./ZEsarUX.app/Contents/Resources/tbblue.mmc /devel
----

Optionally, using `hdfmonkey`, we can replace the original distro `autoexec.bat` for the one availble in `ToInstall/autoexec.bas`. For example:

[source,shell]
----
hdfmonkey put ./ZEsarUX/tbblue.mmc ./ToInstall/autoexec.bat /nextzxos/autoexec.bas
----

On MacOS:

[source,shell]
----
hdfmonkey put ./ZEsarUX.app/Contents/Resources/tbblue.mmc ./ToInstall/autoexec.bat /nextzxos/autoexec.bas
----

<<<

== How to use

=== BAS Files

The tasks and scripts are designed to deal with text files, with `.bas` extension, and encoded using UTF-8, with windows line endings (CRLF).

NextBASIC keywords must be written always in uppercase (this offers compatibility with programs that use variable names similar to keywords).

You can use https://en.wikipedia.org/wiki/Block_Elements[unicode block elements] which will be automatically converted. Also , it is possible to have non-printable characters, using `` ` `` as escape code, and then the desired code, as a decimal or hexadecimal number (in this case preceded by "`x`"). For example, use `` `16`2`17`6`` or `` `x10`x02`x11`x06`` to send red ink and yellow paper codes. This method can be used too to embed little machine code routines inside of REM lines.

A list of Sinclair codes is available https://www.worldofspectrum.org/ZXBasicManual/zxmanappa.html[at this link]. For ZX Spectrum Next codes see appendix A, in the official manual.

NOTE: To launch any of the following tasks, you have to use menu option `Terminal->Run Build Task...` or the equivalente keyboard shortcut (for example: Command+Shitf+B on MacOS).

=== Renumbering

Open the directory "Projects" with Visual Studio Code.

The `tasks.json` file creates a Visual Studio Code task named `Renumber NextBASIC`. When invoked with a `.bas` text file selected, tries to renumber the source code content.

=== Formatting

Open the directory "Projects" with Visual Studio Code.

The `tasks.json` file creates a Visual Studio Code task named `Format NextBASIC`. When invoked with a `.bas` text file selected, tries to format the source code in a uniform way. This means adding (or removing) extra spaces rounding NextBASIC tokens, indenting with spaces line numbers, etc.

WARNING: Automatic code formatting is, at this moment, a beta feature.

CAUTION: Every time that formatting is applied, the previous version of source code is kept as a coopy, with extension `.bak`. If the task is execute twice, you can lose the original source code.

<<<

=== Compiling

Open the directory "Projects" with Visual Studio Code.

The `tasks.json` file creates a couple of Visual Studio Code tasks named `Build ZX Basic` and `Build NextBASIC` that, when invoked with a `.bas` text file selected, creates a `build` directory and, inside of this, a `.bin` file with the compiled program if ZX Basic was selected, or a `.bas` file if NextBASIC. Also, in the case of ZX Basic, a launcher  `.bas` file is created, so it can be launched from the ZX Next Browser, ESXDOS o +3e DOS.

For example, starting with this ZX Basic source file:

       +--Projects/
             |
             +--.vscode/
             |     |
             |     +--tasks.json
             |
             +--Example.bas

After running `Build ZX Basic` we will get:

       +--Projects/
             |
             +--.vscode/
             |     |
             |     +--tasks.json
             |
             +--Example.bas
             |
             +--build/
                  |
                  +-Example.bas
                  +-Example.bin

`.bas` files do not neede to be created in the root of `Projects`, there can be as many subdirectories as you want.

<<<

=== Compiling and executing with emulator

For each of the compiling options, there are also two other tasks named `Build ... And Run (CSpect)` and `Build ... And Run (ZEsarUX)` which can be used to compile, copy the new created files (`.bas` and, possibly, `.bin`) inside the virtual SD for the selected emulator, and then launch the emulator. If the `autoexec.bas` file has also been changed, a small BASIC program will start, where, pressing any key but BREAK will try to start the new program. If you press BREAK, ZX Next browser will be launched instead.

Also, if a file `.filelist` is added, with the same name that the `.bas` file, and with the names of other files inside, the corresponding task will try to copy these files to the SD.

For example, with a ZX Basic file and a `.filelist` file:

       +--Projects/
             |
             +--.vscode/
             |     |
             |     +--tasks.json
             |
             +--Example.bas
             +--Example.filelist
             +--Image1.scr
             +--Image2.scr
             +--Screen.bmp
             +--Screen2.bmp

Where `Example.filelist` has these contents:

        Image1.scr
        Image2.scr
        Screen.bmp

When the task is run, `Example.bas` and `Example.bin` will be copied, and also `Image1.scr`, `Image2.scr` and `Screen.bmp`. But `Screen2.bmp` *won't*.

<<<

=== Command Line Utilities

==== Converting a binary BASIC file (+3DOS) to text

You can use `nextbasic2txt.py` to convert a binary BASIC file (+3DOS o ESXDOS) to text. Syntax is as following:

[source,shell]
----
python3 nextbasic2txt.py -i <binary_file.bas> -o <new_file>
----

==== Convert a file with binary BASIC data to a binary BASIC file (+3DOS)

It is also possible to convert, using `txt2nextbasic.py`, a file with binary BASIC data (e.g., extracted from tape file with Tapir) to a binary BASIC file  (+3DOS o ESXDOS). The syntax to use is:

[source,shell]
----
python3 txt2nextbasic.py -b -i <binary_file> -o <new_file.bas>
----

<<<

== Code Examples

Some source code examples are included with the software distribution.

=== Ellipses.bas

Simple example that takes advantage of the possibility to run software faster with NextOS.

=== Blocks.bas

Demonstration of how you can write a program using usen https://en.wikipedia.org/wiki/Block_Elements[unicode block characters].

=== NextLayer2Scroll

Two basic animation examples using `LAYER`. The first thing that the programs ask for is the number of steps for each full animation loop. Take note tha version v2 makes a calculation step in order to make a more smooth animation.

=== NextSprite

Two exampls using Sprites with NextBASIC. Version v2 uses extended NextOS registers to build a block of anchored sprites (see procedure `CreateRelSprites`), so the animation is also much smoother.

<<<

== Copyright

Copyright (c) 2020-2021 kounch

Permission to use, copy, modify, and/or distribute this software for any purpose with or without fee is hereby granted, provided that the above copyright notice and this permission notice appear in all copies.

THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE
